version: "3.9"
services: 
    db:
        image: postgres
        ports:
            - "5432:5432"
        environment: 
            POSTGRES_PASSWORD: ${DB_PASSWORD}
    pgadmin: 
        image: dpage/pgadmin4
        ports: 
            - "5555:80"
        environment: 
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    web:
        build: .
        depends_on: 
            - db
        ports:
            - "8080:8080"
        environment: 
            DB_USERNAME: postgres
            DB_PASSWORD: ${DB_PASSWORD}
            SECRET_KEY: ${SECRET_KEY}
            DB_HOST_IP: db